--- 
abstract: fast and compact HTML Form Class
author: 
  - Thorsten Domsch, camelcase@gmx.de
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTML-TurboForm
no_index: 
  directory: 
    - inc
    - t
requires: 
  Date::Calc: 0
  Email::Valid: 0
  Imager: 0
  UNIVERSAL::require: 0
  YAML::Syck: 0
version: 0.26
